### ISSUE TITLE
Mandatory columns missing or invalid results in bad error message

### ISSUE THREAD

**Issue by MrNickArcher** [thehappycheese/nickmap-bi#6]
- [ ] When any of the mandatory field wells are not populated, the error message is very poor
- [ ] Because PowerBI's constraints are not working, the user may also enter invalid data types (???)
- [ ] or multiple columns into fields which should only accept a single column.

**Comment by thehappycheese** [comment]
This is now catastrophically broken in v4.1.3 D:
