### ISSUE TITLE
Dragbox selection should clear when filters are applied

### ISSUE THREAD

**Issue by MrNickArcher** [thehappycheese/nickmap-bi#8]
- [x] If features are selected, then some slicer filters away some selected features, the invisible features remain selected and affect the rest of the report.
  - This appears to be happening because the selection is applied before the old features are replaced by freshly downloaded features
- [x] Any update results in the selection disappearing.
- [x] Show user count of selected features
- [ ] Explain to user how to deselect features
- [ ] When drag box selection is disabled, it does not clear the existing selection

**Comment by thehappycheese** [comment]
Explain to user how to deselect features will be handled in the splash screen issue
When drag box selection is disabled, it does not clear the existing selection is also solved by the above. The user can just do it.
